apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-demo
  namespace: default

spec:
  replicas: 2

  selector:
    matchLabels:
      app: nginx-demo

  template:
    metadata:
      labels:
        app: nginx-demo

    spec:

      #Auto Mode provisions capacity based on workload demand, and Auto Mode nodes carry 
      #the label eks.amazonaws.com/compute-type=auto.
      #AWS documents this label specifically for controlling whether a workload runs on EKS Auto Mode nodes.
      nodeSelector:
        eks.amazonaws.com/compute-type: auto

      containers:
        - name: nginx
          image: nginx:alpine

          ports:
            - containerPort: 80

          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"

            limits:
              cpu: "200m"
              memory: "128Mi"